### ISSUE TITLE
Auto close brackets and quotes

### ISSUE THREAD

**Issue by timrspratt** [beyondcode/tinkerwell-suggestions#16]
Would be great if typing `collect(` added the trailing `)` and focussed the cursor within the brackets, like most IDEs do. Would apply for all standard auto-closing pairs, `{, (, [, ', "`.

Thanks!

**Comment by sschlein** [comment]
You can use the IDE plugins for PHPStorm, VSCode and Sublime until this has been added someday. But I also feel your pain every day ...

**Comment by niladam** [comment]
IMHO, i think that's just lazy. I think tinkerwell is for the ones who love to dig in their code.

I do understand it makes it easier, but autocompletion shouldn't be bloating tinkerwell. Basically, it's tinker. It should work like tinker.

**Comment by sschlein** [comment]
We talked about this today and decided to close this issue. If you really want to have this right now, you can use the IDE plugins. 

The problem with auto-closing all kinds of braces is that this is only a fraction of the feature. If we start with braces, we also need to talk about the other auto-closing pairs. But what happens if we auto-close them and put the cursor at a position that you don't expect? What if we auto-close it and then you close the pair with your muscle-memory? Most IDEs overwrite the auto-closed element then. The feature looks small but can have a painful impact on usability.

With our small team, we want to dedicate our time to more important feature and so we are closing this for now.
