### ISSUE TITLE
Error in Output

### ISSUE THREAD

**Issue by samaasi** [beyondcode/tinkerwell-suggestions#182]
Hello guys, i keep getting this error as an out whenever i use laravel 7.

Fatal error: Declaration of Illuminate\Foundation\Application::handle(Symfony\Component\HttpFoundation\Request $request, $type = self::MASTER_REQUEST, $catch = true) must be compatible with Symfony\Component\HttpKernel\HttpKernelInterface::handle(Symfony\Component\HttpFoundation\Request $request, int $type = self::MASTER_REQUEST, bool $catch = true) in /Applications/Tinkerwell.app/Contents/Resources/Laravel/7.0/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 29

**Comment by sschlein** [comment]
Can you please double check if you have selected the correct PHP executable?

**Comment by samaasi** [comment]
Yes i did

**Comment by sschlein** [comment]
Which one is selected?

**Comment by SahinU88** [comment]
Think my issue is related. I'm also getting the same error.

I checked my php-bin executable and it shows to my php7.4 which also runs with my laravel application.

![image](https://user-images.githubusercontent.com/5758310/78713794-16b10800-791b-11ea-97dc-aa1ba51f6b17.png)

Tinkerwell 2.6 installed.

**Comment by sschlein** [comment]
Gives `which php` the same output? Sometimes Tinkerwell detects `usr/bin/php` but PHP is actually `usr/local/bin/php`

**Comment by SahinU88** [comment]
Oh shoot.. how did I missed that? Sry that I bothered you. The php-executable path was not the same as you said.

`which php` showed me `/usr/loacl/bin/php` but the php-executable path in tinkerwell was set to the wrong one (pointing to php7.1)

**So that solves the problem, just as a recap for others**
- make sure that your `php` executable path in tinkerwell and on your system are showing to the correct one
- mine was to set it to `/usr/local/bin/php` which shows to php74

**Comment by sschlein** [comment]
That's actually very common and I have added this to the docs now 🙂

**Comment by SahinU88** [comment]
Oh noice 👌

Guess this issue can be closed then :)
