### ISSUE TITLE
Better stacktraces for errors

### ISSUE THREAD

**Issue by driesvints** [beyondcode/tinkerwell-suggestions#28]
![Screen Shot 2019-11-21 at 11 49 09](https://user-images.githubusercontent.com/594614/69331922-ead80300-0c55-11ea-8d49-4f36016ca528.png)

Woud be cool if the current stacktraces could be better formatted. There's also some cool package you could integrate with. It's called Ignition or something 👀

**Comment by driesvints** [comment]
I also got a flashy yellow just now 😵

![Screen Shot 2019-11-21 at 12 01 33](https://user-images.githubusercontent.com/594614/69332362-d34d4a00-0c56-11ea-923c-1b727160716c.png)

**Comment by mpociot** [comment]
The next version will use collusion for the stacktrace 👍 
![Screen Shot 2019-11-21 at 3 35 42 PM](https://user-images.githubusercontent.com/804684/69349000-57afc500-0c77-11ea-98d9-3a8304844dac.png)

**Comment by driesvints** [comment]
Yasss 💯 

@mpociot thanks!

**Comment by driesvints** [comment]
@mpociot is it also possible to use `word-wrap: break-word;` for the exceptions? So they're not viewed as code lines but a log which you don't need to horizontally scroll?

**Comment by mpociot** [comment]
I’ll take care of that with #17

**Comment by jan-demsar** [comment]
I'm sorry to re-open an old issue, but I am wondering if I need to enable anything else in order to see stacktraces?

I am on version 2.19.0 and all I can see are exception name and message: 

![image](https://user-images.githubusercontent.com/328756/147946200-f4b1cb3a-aa58-4771-94f2-ec1348a5309c.png)

![image](https://user-images.githubusercontent.com/328756/147946335-630d4115-7e50-4a10-b288-c26c7186a318.png)

Thanks!
