### ISSUE TITLE
Atom.io IDE Support

### ISSUE THREAD

**Issue by repat** [beyondcode/tinkerwell-suggestions#33]
As mentioned here: https://twitter.com/repat123/status/1196825603888099330

* https://atom.io/packages/ide-php
* https://ide.atom.io/

**Comment by sschlein** [comment]
Are there any stats how people are using Atom in comparison with the other editors? I have the feeling that Atom is an edge case and it creates too much overhead for us to support it.

**Comment by sschlein** [comment]
Thanks for your suggestion.

I'm closing this issue because I don't think this will get a priority anytime soon. We are a small team and we are happy that we are able to provide Tinkerwell for 3 operating systems and release new major features regularly. The request itself doesn't take much time initially but we need to maintain it for years and don't see the benefit for the overall user base.

**Comment by repat** [comment]
Fair enough! Thanks for considering it :-)
