### ISSUE TITLE
Hotkey to disable/enable auto-evaluation

### ISSUE THREAD

**Issue by sschlein** [beyondcode/tinkerwell-suggestions#4]

**Comment by kristremblay** [comment]
Click the cog in the bottom left of the ui and remove the check from `Auto evaluate script`.

**Comment by mpociot** [comment]
Well I think it’s cool for non destructive tasks. We automatically disable it if you connect via ssh though. And if you want to disable it yourself, just toggle it off in the settings 🤷‍♂️

**Comment by kristremblay** [comment]
It is definitely cool for non-destructive tasks, and I really do love this app :)

I just have an aversion to what my colleague refers to as foot-gun scenarios; there is the edge case where Joe might have his dev .env pointing to production data which, while awful and gross, is a mistake a lot of juniors+ make.

**Comment by squatto** [comment]
_@mpociot this suggestion was sent in by me by email prior to this suggestion repo existing and Sebastian added it here for me. I wanted to include my original suggestion text so that you could see where I was coming from:_

Add a hotkey to enable/disable auto script evaluation. This would be helpful in situations like the attached video. While building eloquent queries it's useful to leave a model in the output so that you can see the model properties, but when you start typing the output is cleared. I find myself going into the settings, turning off "auto evaluate script", adding more to the eloquent query, then turning it back on and continuing on. If there was a hotkey to toggle the setting that would be super useful and wouldn't require having to use my mouse.

![auto-evaluate-during-query](https://user-images.githubusercontent.com/748444/73495300-7f0bc800-4373-11ea-939b-4485d5fa1d71.gif)

**Comment by sschlein** [comment]
Thanks for your suggestion! It's a feature that we can implement in the future but I don't think that it becomes a priority anytime soon - so I'm closing this issue for now.
