### ISSUE TITLE
Installation via homebrew cask.

### ISSUE THREAD

**Issue by mathieutu** [beyondcode/tinkerwell-suggestions#40]
Just a ticket to keep a trace of that.

<img width="579" alt="Screenshot 2019-11-27 at 21 16 16" src="https://user-images.githubusercontent.com/11351322/69759597-ca7edb80-1162-11ea-8bbb-aa5c1d6f63a2.png">

https://twitter.com/marcelpociot/status/1199787246620164096

Thanks for the work.
👋

**Comment by marijnbent** [comment]
Which workflow do you use to run this within alfred?

**Comment by mathieutu** [comment]
@marijnbent https://github.com/fniephaus/alfred-homebrew

**Comment by sschlein** [comment]
Thanks for your suggestion.

I'm closing this issue because I don't think this will get a priority anytime soon. We are a small team and we are happy that we are able to provide Tinkerwell for 3 operating systems and release new major features regularly. The request itself doesn't take much time initially but we need to maintain it for years and don't see the benefit for the overall user base.

**Comment by Gummibeer** [comment]
@sschlein the benefit would be to be able to install it via `brew bundle` with a `Brewfile`.
Because this app targets developers this is a common approach to install all required software on a new machine and keep them in sync.
