### ISSUE TITLE
Tinkerwell v1.2.0  Call to undefined method Psy/Shell::getLastExecSuccess() 

### ISSUE THREAD

**Issue by davidstefando** [beyondcode/tinkerwell-suggestions#49]
Hi,

I'm using tinkerwell v1.2.0
When I'm try to run code, I got this error message

PHP Error:  Call to undefined method Psy/Shell::getLastExecSuccess() in /tmp/tinker.php on line 52

Thanks,
Best Regards
David Pratama

**Comment by sschlein** [comment]
Hey,

it sounds like you are using Tinkerwell on an older Laravel version or a non-Laravel project. We don't support generic PHP applications yet but if it's an older Laravel project, you can upgrade the underlying https://psysh.org/ package in your application and it should work. Normally, it's save to upgrade it because it's only used for Laravel tinker.

:)

**Comment by allaniftrue** [comment]
Tinkerwell was working on my machine since I bought it. When I changed to another machine running the same project I am now encountering this error.

**Comment by sschlein** [comment]
Please give 1.2 a shot: https://tinkerwell.app/download/Tinkerwell_1.2.0.dmg

We are also about to release 2.0 that also solves this issue.

**Comment by allaniftrue** [comment]
hopefully, it will be out soon. because I'm back on the CLI for the past days. Thanks!

**Comment by sschlein** [comment]
It is :)

You can't update it via the auto-updater but there is a download on the site in the release section.
