### ISSUE TITLE
Ignore comments at end of file

### ISSUE THREAD

**Issue by sschlein** [beyondcode/tinkerwell-suggestions#5]
If there is a comment at the end of the file, this line will be used to determine the output–and this output is always empty.

Example:
![attachment-1](https://user-images.githubusercontent.com/2911113/69227785-b9dace00-0b82-11ea-877c-056bc3d4d186.png)

**Comment by ryangjchandler** [comment]
+1 noticed this today

**Comment by zaratedev** [comment]
Same problem +1  👀

**Comment by squatto** [comment]
_@mpociot This is another that came from me before this repo existed (like #4). My original text images are below._

Ignore commented lines when determining what the last command is (aka what output should be shown). An example can be seen here:

**No commented lines = output**

![no-commented-lines](https://user-images.githubusercontent.com/748444/73495660-386a9d80-4374-11ea-8dc4-ed292b2b859a.png)

**Commented lines at the end of the script = no output**

![commented-lines](https://user-images.githubusercontent.com/748444/73495669-3b658e00-4374-11ea-8716-0581ffa23e04.png)

I realize that this is happening because the output of a comment in tinker is nothing, but you could remove commented lines before running the commands through tinker (since they're a noop anyway).

**Comment by devyk** [comment]
Having the same problem

**Comment by sschlein** [comment]
This will be fixed in the next release :)
