### ISSUE TITLE
Installation via Scoop

### ISSUE THREAD

**Issue by owenvoke** [beyondcode/tinkerwell-suggestions#87]
Similar to #40, I tend to use [Scoop](https://scoop.sh) for installing Windows applications. It would be nice to have Tinkerwell included in [the Scoop Extras bucket](https://github.com/lukesampson/scoop-extras).

I've started working on a Scoop manifest for it in my custom Scoop bucket.
https://github.com/owenvoke/scoop-bucket/blob/feature/tinkerwell/bucket/tinkerwell.json

However, the issue I've found is with the auto-update functionality in Tinkerwell. It appears to install it into a different location by default (I mentioned about this [on Twitter](https://twitter.com/owenvoke/status/1221738170418651137)).

![image](https://user-images.githubusercontent.com/1899334/73652100-f300e580-467d-11ea-89e5-b4a0c5608e60.png)
![image](https://user-images.githubusercontent.com/1899334/73652213-42dfac80-467e-11ea-9990-57bea79cff46.png)

I guess this issue could be resolved using a config or env option.

**Comment by sschlein** [comment]
Thanks for your suggestion.

I'm closing this issue because I don't think this will get a priority anytime soon. We are a small team and we are happy that we are able to provide Tinkerwell for 3 operating systems and release new major features regularly. The request itself doesn't take much time initially but we need to maintain it for years and don't see the benefit for the overall user base.

**Comment by owenvoke** [comment]
No problem. Thanks for the great app!
