### ISSUE TITLE
keyboard shortcut for changing font size

### ISSUE THREAD

**Issue by vesper8** [beyondcode/tinkerwell-suggestions#88]
I've noticed something un usual in Tinkerwell (OSX). The CMD-minus works for decreasing the font-size but the CMD-plus does not work for increasing it

I've confirmed this is not a keyboard problem as the same shortcuts work perfectly well in Sublime Text and VSCode, so it seems to be a Tinkerwell issue.

Thankfully I was able to re-adjust the font-size by using the preference pane

**Comment by mpociot** [comment]
Hm okay...must be something related to the keyboard layout. It's working fine on my german qwertz keyboard with CMD-plus

**Comment by vesper8** [comment]
hrmm.. but how would that explain that the keys work fine in Sublime Text and VSCode.. and Chrome.. etc.. CMD-plus works in pretty much every app except Tinkerwell

**Comment by sschlein** [comment]
It also seems that no one else has this problem and we are not able to debug it.

I'm closing this issue to cleanup this repository a bit as it is not a critical bug that makes the app unuseable :)

**Comment by desaintflorent** [comment]
I guess it's a keyboard problem because I have a similar issue :

I have a french AZERTY keyboard and when I hit undo shortcut : CMD-Z , the current tab is closing...
If I do undo from the textual menu it's working well. 
So I guess the app is not taking the user keyboard type in consideration.

Would be great to have this bug fixed, because I can't use this wonderfull app if I loose my work every time I hit CMD-Z :/

**Comment by vesper8** [comment]
Weird... in my case CMD-minus works to decrease the font-size but CMD-plus does not work to increase it, even though those hotkeys work perfectly well in every other application

I do have a Macbook Pro with a french-bilingual keyboard, however it is set to use the US keyboard and I don't actually make use of the french keys. Also the problem occurs whether I type CMD-plus on the Macbook itself or on a Logitech bluetooth keyboard
